on test => sub { requires 'Test::Exception' };
